//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacebookApplicationUsingGraphAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_post
    {
        public int id { get; set; }
        public string sharer_facebook_id { get; set; }
        public string facebook_post_id { get; set; }
        public Nullable<bool> like_post { get; set; }
        public Nullable<bool> share_post { get; set; }
        public byte[] database_entry_date { get; set; }
    }
}
